services:
    training_user_naming.provider.entity_name_decorator:
        class: 'Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator'
        decorates: 'oro_locale.entity_name_provider'
        decoration_inner_name: 'oro_locale.entity_name_provider.original'
        public: false
        arguments:
            - '@oro_locale.entity_name_provider.original'
        tags:
            - { name: oro_entity.name_provider, priority: -80 }

    training_user_naming.event_listener.user_view_naming:
        class: 'Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener'
        arguments:
            - '@doctrine'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }
